### ISSUE TITLE
Add detection for sites.google.com phishing

### ISSUE THREAD

**Issue by botherder** [phishdetect/phishdetect#3]
Similarly to #2, there are phishing sites being hosted for example on sites.google.com and currently those would not be marked as suspicious because of the fact that they are hosted on a whitelisted domain (google.com).

We need to adapt PhishDetect detection to take this situation into account.

**Comment by pplanel** [comment]
Maybe add the domain to suspicious slice in https://github.com/phishdetect/phishdetect/blob/master/brand/google.go?

**Comment by botherder** [comment]
That would block any visit to `site.google.com`. Instead we want to treat it as some sort of exception from the safelisting that would normally happen.

**Comment by botherder** [comment]
This is addressed by 0c3fa8d949d3a27f19447ce5b10d95f30ce6a64e.
